{
  imports = [
    ./archive.nix
    ./bluetooth.nix
    ./console.nix
    ./coolercontrol.nix
    ./droidcam.nix
    ./flatpak.nix
    ./gaming.nix
    ./gvfs.nix
    ./i18n.nix
    ./kernel.nix
    ./mullvad.nix
    ./networking.nix
    ./nh.nix
    ./nix.nix
    ./pipewire.nix
    ./ssh.nix
    ./timezone.nix
    ./wacom.nix
    ./x11.nix
  ];
}
