pragma Singleton
import Quickshell
import QtQuick

Singleton {
  readonly property color background: "#151218"
  readonly property color error: "#ffb4ab"
  readonly property color error_container: "#93000a"
  readonly property color inverse_on_surface: "#332f35"
  readonly property color inverse_primary: "#6c538c"
  readonly property color inverse_surface: "#e7e0e8"
  readonly property color on_background: "#e7e0e8"
  readonly property color on_error: "#690005"
  readonly property color on_error_container: "#ffdad6"
  readonly property color on_primary: "#3c255a"
  readonly property color on_primary_container: "#eedcff"
  readonly property color on_primary_fixed: "#260d44"
  readonly property color on_primary_fixed_variant: "#533b72"
  readonly property color on_secondary: "#352d40"
  readonly property color on_secondary_container: "#ebddf7"
  readonly property color on_secondary_fixed: "#20182a"
  readonly property color on_secondary_fixed_variant: "#4c4357"
  readonly property color on_surface: "#e7e0e8"
  readonly property color on_surface_variant: "#ccc4cf"
  readonly property color on_tertiary: "#4b252d"
  readonly property color on_tertiary_container: "#ffd9de"
  readonly property color on_tertiary_fixed: "#321018"
  readonly property color on_tertiary_fixed_variant: "#653b43"
  readonly property color outline: "#958e99"
  readonly property color outline_variant: "#4a454e"
  readonly property color primary: "#d8bafb"
  readonly property color primary_container: "#533b72"
  readonly property color primary_fixed: "#eedcff"
  readonly property color primary_fixed_dim: "#d8bafb"
  readonly property color scrim: "#000000"
  readonly property color secondary: "#cfc1da"
  readonly property color secondary_container: "#4c4357"
  readonly property color secondary_fixed: "#ebddf7"
  readonly property color secondary_fixed_dim: "#cfc1da"
  readonly property color shadow: "#000000"
  readonly property color surface: "#151218"
  readonly property color surface_bright: "#3b383e"
  readonly property color surface_container: "#211e24"
  readonly property color surface_container_high: "#2c292f"
  readonly property color surface_container_highest: "#373339"
  readonly property color surface_container_low: "#1d1a20"
  readonly property color surface_container_lowest: "#100d12"
  readonly property color surface_dim: "#151218"
  readonly property color surface_tint: "#d8bafb"
  readonly property color surface_variant: "#4a454e"
  readonly property color tertiary: "#f2b7c1"
  readonly property color tertiary_container: "#653b43"
  readonly property color tertiary_fixed: "#ffd9de"
  readonly property color tertiary_fixed_dim: "#f2b7c1"
}
